// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: accounting/v1/accounting.proto

package accountingv1

import (
	reflect "reflect"
	v1 "rtb-platform/pb/common/v1"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DebitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Amount        *v1.Money              `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BidId         string                 `protobuf:"bytes,3,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"` // идентификатор аукциона для идемпотентности
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitRequest) Reset() {
	*x = DebitRequest{}
	mi := &file_accounting_v1_accounting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitRequest) ProtoMessage() {}

func (x *DebitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_v1_accounting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitRequest.ProtoReflect.Descriptor instead.
func (*DebitRequest) Descriptor() ([]byte, []int) {
	return file_accounting_v1_accounting_proto_rawDescGZIP(), []int{0}
}

func (x *DebitRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *DebitRequest) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *DebitRequest) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

type DebitResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RemainingBalance *v1.Money              `protobuf:"bytes,2,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"`
	Error            string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DebitResponse) Reset() {
	*x = DebitResponse{}
	mi := &file_accounting_v1_accounting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitResponse) ProtoMessage() {}

func (x *DebitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_v1_accounting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitResponse.ProtoReflect.Descriptor instead.
func (*DebitResponse) Descriptor() ([]byte, []int) {
	return file_accounting_v1_accounting_proto_rawDescGZIP(), []int{1}
}

func (x *DebitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DebitResponse) GetRemainingBalance() *v1.Money {
	if x != nil {
		return x.RemainingBalance
	}
	return nil
}

func (x *DebitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_accounting_v1_accounting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_v1_accounting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_accounting_v1_accounting_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *v1.Money              `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_accounting_v1_accounting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_v1_accounting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_accounting_v1_accounting_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetBalance() *v1.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

var File_accounting_v1_accounting_proto protoreflect.FileDescriptor

const file_accounting_v1_accounting_proto_rawDesc = "" +
	"\n" +
	"\x1eaccounting/v1/accounting.proto\x12\raccounting.v1\x1a\x15common/v1/money.proto\"p\n" +
	"\fDebitRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12(\n" +
	"\x06amount\x18\x02 \x01(\v2\x10.common.v1.MoneyR\x06amount\x12\x15\n" +
	"\x06bid_id\x18\x03 \x01(\tR\x05bidId\"~\n" +
	"\rDebitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\x11remaining_balance\x18\x02 \x01(\v2\x10.common.v1.MoneyR\x10remainingBalance\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"4\n" +
	"\x11GetBalanceRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"@\n" +
	"\x12GetBalanceResponse\x12*\n" +
	"\abalance\x18\x01 \x01(\v2\x10.common.v1.MoneyR\abalance2\xaa\x01\n" +
	"\x11AccountingService\x12B\n" +
	"\x05Debit\x12\x1b.accounting.v1.DebitRequest\x1a\x1c.accounting.v1.DebitResponse\x12Q\n" +
	"\n" +
	"GetBalance\x12 .accounting.v1.GetBalanceRequest\x1a!.accounting.v1.GetBalanceResponseB7Z5github.com/rtb-platform/pb/accounting/v1;accountingv1b\x06proto3"

var (
	file_accounting_v1_accounting_proto_rawDescOnce sync.Once
	file_accounting_v1_accounting_proto_rawDescData []byte
)

func file_accounting_v1_accounting_proto_rawDescGZIP() []byte {
	file_accounting_v1_accounting_proto_rawDescOnce.Do(func() {
		file_accounting_v1_accounting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounting_v1_accounting_proto_rawDesc), len(file_accounting_v1_accounting_proto_rawDesc)))
	})
	return file_accounting_v1_accounting_proto_rawDescData
}

var file_accounting_v1_accounting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_accounting_v1_accounting_proto_goTypes = []any{
	(*DebitRequest)(nil),       // 0: accounting.v1.DebitRequest
	(*DebitResponse)(nil),      // 1: accounting.v1.DebitResponse
	(*GetBalanceRequest)(nil),  // 2: accounting.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 3: accounting.v1.GetBalanceResponse
	(*v1.Money)(nil),           // 4: common.v1.Money
}
var file_accounting_v1_accounting_proto_depIdxs = []int32{
	4, // 0: accounting.v1.DebitRequest.amount:type_name -> common.v1.Money
	4, // 1: accounting.v1.DebitResponse.remaining_balance:type_name -> common.v1.Money
	4, // 2: accounting.v1.GetBalanceResponse.balance:type_name -> common.v1.Money
	0, // 3: accounting.v1.AccountingService.Debit:input_type -> accounting.v1.DebitRequest
	2, // 4: accounting.v1.AccountingService.GetBalance:input_type -> accounting.v1.GetBalanceRequest
	1, // 5: accounting.v1.AccountingService.Debit:output_type -> accounting.v1.DebitResponse
	3, // 6: accounting.v1.AccountingService.GetBalance:output_type -> accounting.v1.GetBalanceResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_accounting_v1_accounting_proto_init() }
func file_accounting_v1_accounting_proto_init() {
	if File_accounting_v1_accounting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounting_v1_accounting_proto_rawDesc), len(file_accounting_v1_accounting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounting_v1_accounting_proto_goTypes,
		DependencyIndexes: file_accounting_v1_accounting_proto_depIdxs,
		MessageInfos:      file_accounting_v1_accounting_proto_msgTypes,
	}.Build()
	File_accounting_v1_accounting_proto = out.File
	file_accounting_v1_accounting_proto_goTypes = nil
	file_accounting_v1_accounting_proto_depIdxs = nil
}
