// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auction/v1/auction.proto

package auctionv1

import (
	v1 "github.com/rtb-platform/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ip             string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent      string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Lat            float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng            float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	CampaignIds    []string               `protobuf:"bytes,6,rep,name=campaign_ids,json=campaignIds,proto3" json:"campaign_ids,omitempty"`          // если нужно ограничить кампании
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // для предотвращения дублей
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_auction_v1_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_v1_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_auction_v1_auction_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BidRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BidRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *BidRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *BidRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *BidRequest) GetCampaignIds() []string {
	if x != nil {
		return x.CampaignIds
	}
	return nil
}

func (x *BidRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type BidResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CampaignId  string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	BidPrice    *v1.Money              `protobuf:"bytes,2,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"` // ставка в копейках
	CreativeUrl string                 `protobuf:"bytes,3,opt,name=creative_url,json=creativeUrl,proto3" json:"creative_url,omitempty"`
	// опционально: причина отказа, если аукцион не состоялся
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_auction_v1_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_v1_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_auction_v1_auction_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *BidResponse) GetBidPrice() *v1.Money {
	if x != nil {
		return x.BidPrice
	}
	return nil
}

func (x *BidResponse) GetCreativeUrl() string {
	if x != nil {
		return x.CreativeUrl
	}
	return ""
}

func (x *BidResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_auction_v1_auction_proto protoreflect.FileDescriptor

const file_auction_v1_auction_proto_rawDesc = "" +
	"\n" +
	"\x18auction/v1/auction.proto\x12\n" +
	"auction.v1\x1a\x15common/v1/money.proto\"\xc8\x01\n" +
	"\n" +
	"BidRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12!\n" +
	"\fcampaign_ids\x18\x06 \x03(\tR\vcampaignIds\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"\x96\x01\n" +
	"\vBidResponse\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12-\n" +
	"\tbid_price\x18\x02 \x01(\v2\x10.common.v1.MoneyR\bbidPrice\x12!\n" +
	"\fcreative_url\x18\x03 \x01(\tR\vcreativeUrl\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2H\n" +
	"\x0eAuctionService\x126\n" +
	"\x03Bid\x12\x16.auction.v1.BidRequest\x1a\x17.auction.v1.BidResponseB1Z/github.com/rtb-platform/pb/auction/v1;auctionv1b\x06proto3"

var (
	file_auction_v1_auction_proto_rawDescOnce sync.Once
	file_auction_v1_auction_proto_rawDescData []byte
)

func file_auction_v1_auction_proto_rawDescGZIP() []byte {
	file_auction_v1_auction_proto_rawDescOnce.Do(func() {
		file_auction_v1_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_v1_auction_proto_rawDesc), len(file_auction_v1_auction_proto_rawDesc)))
	})
	return file_auction_v1_auction_proto_rawDescData
}

var file_auction_v1_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auction_v1_auction_proto_goTypes = []any{
	(*BidRequest)(nil),  // 0: auction.v1.BidRequest
	(*BidResponse)(nil), // 1: auction.v1.BidResponse
	(*v1.Money)(nil),    // 2: common.v1.Money
}
var file_auction_v1_auction_proto_depIdxs = []int32{
	2, // 0: auction.v1.BidResponse.bid_price:type_name -> common.v1.Money
	0, // 1: auction.v1.AuctionService.Bid:input_type -> auction.v1.BidRequest
	1, // 2: auction.v1.AuctionService.Bid:output_type -> auction.v1.BidResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auction_v1_auction_proto_init() }
func file_auction_v1_auction_proto_init() {
	if File_auction_v1_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_v1_auction_proto_rawDesc), len(file_auction_v1_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auction_v1_auction_proto_goTypes,
		DependencyIndexes: file_auction_v1_auction_proto_depIdxs,
		MessageInfos:      file_auction_v1_auction_proto_msgTypes,
	}.Build()
	File_auction_v1_auction_proto = out.File
	file_auction_v1_auction_proto_goTypes = nil
	file_auction_v1_auction_proto_depIdxs = nil
}
