// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	reflect "reflect"
	v1 "rtb-platform/pb/common/v1"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Dimensions    []string               `protobuf:"bytes,3,rep,name=dimensions,proto3" json:"dimensions,omitempty"` // например: campaign_id, device_type
	Metrics       []string               `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`       // impressions, clicks, spend
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ReportRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ReportRequest) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *ReportRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ReportRow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DimensionValues map[string]string      `protobuf:"bytes,1,rep,name=dimension_values,json=dimensionValues,proto3" json:"dimension_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MetricValues    map[string]float64     `protobuf:"bytes,2,rep,name=metric_values,json=metricValues,proto3" json:"metric_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportRow) Reset() {
	*x = ReportRow{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRow) ProtoMessage() {}

func (x *ReportRow) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRow.ProtoReflect.Descriptor instead.
func (*ReportRow) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *ReportRow) GetDimensionValues() map[string]string {
	if x != nil {
		return x.DimensionValues
	}
	return nil
}

func (x *ReportRow) GetMetricValues() map[string]float64 {
	if x != nil {
		return x.MetricValues
	}
	return nil
}

type ForecastRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	History []float64              `protobuf:"fixed64,1,rep,packed,name=history,proto3" json:"history,omitempty"` // временной ряд
	Horizon int32                  `protobuf:"varint,2,opt,name=horizon,proto3" json:"horizon,omitempty"`
	// параметры модели (опционально)
	Alpha         float64 `protobuf:"fixed64,3,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta          float64 `protobuf:"fixed64,4,opt,name=beta,proto3" json:"beta,omitempty"`
	Gamma         float64 `protobuf:"fixed64,5,opt,name=gamma,proto3" json:"gamma,omitempty"`
	Period        int32   `protobuf:"varint,6,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastRequest) Reset() {
	*x = ForecastRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastRequest) ProtoMessage() {}

func (x *ForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastRequest.ProtoReflect.Descriptor instead.
func (*ForecastRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *ForecastRequest) GetHistory() []float64 {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ForecastRequest) GetHorizon() int32 {
	if x != nil {
		return x.Horizon
	}
	return 0
}

func (x *ForecastRequest) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *ForecastRequest) GetBeta() float64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *ForecastRequest) GetGamma() float64 {
	if x != nil {
		return x.Gamma
	}
	return 0
}

func (x *ForecastRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type ForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecast      []float64              `protobuf:"fixed64,1,rep,packed,name=forecast,proto3" json:"forecast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastResponse) Reset() {
	*x = ForecastResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastResponse) ProtoMessage() {}

func (x *ForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastResponse.ProtoReflect.Descriptor instead.
func (*ForecastResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *ForecastResponse) GetForecast() []float64 {
	if x != nil {
		return x.Forecast
	}
	return nil
}

type FactorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*v1.UserProfile      `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // или матрица признаков
	NComponents   int32                  `protobuf:"varint,2,opt,name=n_components,json=nComponents,proto3" json:"n_components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorRequest) Reset() {
	*x = FactorRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorRequest) ProtoMessage() {}

func (x *FactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorRequest.ProtoReflect.Descriptor instead.
func (*FactorRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *FactorRequest) GetUsers() []*v1.UserProfile {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FactorRequest) GetNComponents() int32 {
	if x != nil {
		return x.NComponents
	}
	return 0
}

type FactorResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExplainedVarianceRatio []float64              `protobuf:"fixed64,1,rep,packed,name=explained_variance_ratio,json=explainedVarianceRatio,proto3" json:"explained_variance_ratio,omitempty"`
	Loadings               []float64              `protobuf:"fixed64,2,rep,packed,name=loadings,proto3" json:"loadings,omitempty"` // можно передавать матрицу
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FactorResponse) Reset() {
	*x = FactorResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorResponse) ProtoMessage() {}

func (x *FactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorResponse.ProtoReflect.Descriptor instead.
func (*FactorResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *FactorResponse) GetExplainedVarianceRatio() []float64 {
	if x != nil {
		return x.ExplainedVarianceRatio
	}
	return nil
}

func (x *FactorResponse) GetLoadings() []float64 {
	if x != nil {
		return x.Loadings
	}
	return nil
}

var File_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1canalytics/v1/analytics.proto\x12\fanalytics.v1\x1a\x15common/v1/money.proto\x1a\x14common/v1/user.proto\"\x83\x01\n" +
	"\rReportRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x03(\tR\n" +
	"dimensions\x12\x18\n" +
	"\ametrics\x18\x04 \x03(\tR\ametrics\"\xb9\x02\n" +
	"\tReportRow\x12W\n" +
	"\x10dimension_values\x18\x01 \x03(\v2,.analytics.v1.ReportRow.DimensionValuesEntryR\x0fdimensionValues\x12N\n" +
	"\rmetric_values\x18\x02 \x03(\v2).analytics.v1.ReportRow.MetricValuesEntryR\fmetricValues\x1aB\n" +
	"\x14DimensionValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x9d\x01\n" +
	"\x0fForecastRequest\x12\x18\n" +
	"\ahistory\x18\x01 \x03(\x01R\ahistory\x12\x18\n" +
	"\ahorizon\x18\x02 \x01(\x05R\ahorizon\x12\x14\n" +
	"\x05alpha\x18\x03 \x01(\x01R\x05alpha\x12\x12\n" +
	"\x04beta\x18\x04 \x01(\x01R\x04beta\x12\x14\n" +
	"\x05gamma\x18\x05 \x01(\x01R\x05gamma\x12\x16\n" +
	"\x06period\x18\x06 \x01(\x05R\x06period\".\n" +
	"\x10ForecastResponse\x12\x1a\n" +
	"\bforecast\x18\x01 \x03(\x01R\bforecast\"`\n" +
	"\rFactorRequest\x12,\n" +
	"\x05users\x18\x01 \x03(\v2\x16.common.v1.UserProfileR\x05users\x12!\n" +
	"\fn_components\x18\x02 \x01(\x05R\vnComponents\"f\n" +
	"\x0eFactorResponse\x128\n" +
	"\x18explained_variance_ratio\x18\x01 \x03(\x01R\x16explainedVarianceRatio\x12\x1a\n" +
	"\bloadings\x18\x02 \x03(\x01R\bloadings2\xef\x01\n" +
	"\x10AnalyticsService\x12C\n" +
	"\tGetReport\x12\x1b.analytics.v1.ReportRequest\x1a\x17.analytics.v1.ReportRow0\x01\x12I\n" +
	"\bForecast\x12\x1d.analytics.v1.ForecastRequest\x1a\x1e.analytics.v1.ForecastResponse\x12K\n" +
	"\x0eFactorAnalysis\x12\x1b.analytics.v1.FactorRequest\x1a\x1c.analytics.v1.FactorResponseB5Z3github.com/rtb-platform/pb/analytics/v1;analyticsv1b\x06proto3"

var (
	file_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_analytics_v1_analytics_proto_rawDescData []byte
)

func file_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_analytics_v1_analytics_proto_rawDescData
}

var file_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_analytics_v1_analytics_proto_goTypes = []any{
	(*ReportRequest)(nil),    // 0: analytics.v1.ReportRequest
	(*ReportRow)(nil),        // 1: analytics.v1.ReportRow
	(*ForecastRequest)(nil),  // 2: analytics.v1.ForecastRequest
	(*ForecastResponse)(nil), // 3: analytics.v1.ForecastResponse
	(*FactorRequest)(nil),    // 4: analytics.v1.FactorRequest
	(*FactorResponse)(nil),   // 5: analytics.v1.FactorResponse
	nil,                      // 6: analytics.v1.ReportRow.DimensionValuesEntry
	nil,                      // 7: analytics.v1.ReportRow.MetricValuesEntry
	(*v1.UserProfile)(nil),   // 8: common.v1.UserProfile
}
var file_analytics_v1_analytics_proto_depIdxs = []int32{
	6, // 0: analytics.v1.ReportRow.dimension_values:type_name -> analytics.v1.ReportRow.DimensionValuesEntry
	7, // 1: analytics.v1.ReportRow.metric_values:type_name -> analytics.v1.ReportRow.MetricValuesEntry
	8, // 2: analytics.v1.FactorRequest.users:type_name -> common.v1.UserProfile
	0, // 3: analytics.v1.AnalyticsService.GetReport:input_type -> analytics.v1.ReportRequest
	2, // 4: analytics.v1.AnalyticsService.Forecast:input_type -> analytics.v1.ForecastRequest
	4, // 5: analytics.v1.AnalyticsService.FactorAnalysis:input_type -> analytics.v1.FactorRequest
	1, // 6: analytics.v1.AnalyticsService.GetReport:output_type -> analytics.v1.ReportRow
	3, // 7: analytics.v1.AnalyticsService.Forecast:output_type -> analytics.v1.ForecastResponse
	5, // 8: analytics.v1.AnalyticsService.FactorAnalysis:output_type -> analytics.v1.FactorResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_analytics_v1_analytics_proto_init() }
func file_analytics_v1_analytics_proto_init() {
	if File_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_analytics_v1_analytics_proto = out.File
	file_analytics_v1_analytics_proto_goTypes = nil
	file_analytics_v1_analytics_proto_depIdxs = nil
}
